### ISSUE TITLE
Error in dual-NIC, dual-IP situation

### ISSUE THREAD

**Issue by sdrose** [niwo/cloudstack-cli#13]
Hello Nik
I am trying to figure out the stack .yml format for creating a VM with 2 networks, each with its own specific IP.  The below format doesn't work ...

---
  name: "web_stack-a"
  description: "Web Application Stack"
  version: "1.0"
  zone: "DC-ZRH-1"
  group: "my_web_stack"
  keypair: "mykeypair"
  servers:
    -
      name: "db-01"
      description: "PostgreSQL Master"
      iso: "CentOS-7-x64"
      disk_offering: "Perf Storage"
      disk_size: "5"
      offering: "2cpu_4gb"
      ip_address:
        - 10.100.1.25
        - 10.100.2.25
      networks:
        - "server_network"
        - "storage_network"

I've also tried:
  servers:
    -
      name: "db-01"
      description: "PostgreSQL Master"
      iso: "CentOS-7-x64"
      disk_offering: "Perf Storage"
      disk_size: "5"
      offering: "2cpu_4gb"
        - 
           ip_address: 10.100.1.25
           networks: "server_network"
        -
           ip_address: 10.100.2.25
           networks: "storage_network"

as well as some other iterations. 

For the top-listed example, I receive:
ERROR:  ApiError - Status 431:  Invalid Specified IPv4 Address ["x.x.1.109", "x.x.2.109"]
(you know, x.x being the first 2 octets of the real IP ....)

**Comment by niwo** [comment]
Hi Dave,

Support for IP configurations on multiple interfaces in CloudStack has to be done using the "iptonetworklist" attribute which wasn't implemented in cloudstack-cli so far.

I added this feature in v1.5.2 (f0f7d5d1fd3e97abc43c9658b732c95c486433fe).

You can use it like this in a stack file:

```yaml
---
  name: "web_stack_a"
  description: "Web Application Stack"
  version: "1.0"
  zone: "ZUERICH_EQ"
  project: "Playground"
  group: "my_web_stack"
  servers:
    - name: "web-01"
      description: "webserver"
      iso: "CentOS-7.0-x64"
      offering: "2cpu_4gb"
      ip_network_list:
        - name: FrontendNetwork
          ip: 10.101.64.42
        - name: BackendNetwork
          ip: 10.102.1.11 
```

Cheers,
Nik
